from enum import StrEnum


class Role(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    MATCHMAKER = "MATCHMAKER"
    MALE_USER = "MALE_USER"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    BLOCKED = "BLOCKED"


class VerificationStatus(StrEnum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


class FemaleLeadStatus(StrEnum):
    NEW = "NEW"
    ASSIGNED = "ASSIGNED"
    CONTACTED = "CONTACTED"
    PROFILE_CREATED = "PROFILE_CREATED"
    CLOSED = "CLOSED"


class FemaleProfileStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    HIDDEN = "HIDDEN"
    MATCHED = "MATCHED"
    ARCHIVED = "ARCHIVED"


class ContactPreference(StrEnum):
    GUARDIAN_FIRST = "GUARDIAN_FIRST"
    FAMILIES = "FAMILIES"
    MATCHMAKER = "MATCHMAKER"
    VIRTUAL_WITH_GUARDIAN = "VIRTUAL_WITH_GUARDIAN"
    OTHER = "OTHER"


class PaymentStatus(StrEnum):
    PENDING = "PENDING"
    PAID = "PAID"
    WAIVED = "WAIVED"
    REFUNDED = "REFUNDED"


class Decision(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    NEED_MORE_INFO = "NEED_MORE_INFO"


class MatchCaseStatus(StrEnum):
    CANDIDATE_SELECTED = "CANDIDATE_SELECTED"
    MALE_VERIFICATION = "MALE_VERIFICATION"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    READY_TO_CONTACT_FEMALE = "READY_TO_CONTACT_FEMALE"
    WAITING_FEMALE = "WAITING_FEMALE"
    FEMALE_ACCEPTED = "FEMALE_ACCEPTED"
    WAITING_MALE = "WAITING_MALE"
    MUTUAL_ACCEPTANCE = "MUTUAL_ACCEPTANCE"
    MEETING_SCHEDULED = "MEETING_SCHEDULED"
    MEETING_COMPLETED = "MEETING_COMPLETED"
    FOLLOW_UP = "FOLLOW_UP"
    SERIOUS_CONTACT = "SERIOUS_CONTACT"
    ENGAGED = "ENGAGED"
    MARRIED = "MARRIED"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class MeetingType(StrEnum):
    VIRTUAL = "VIRTUAL"
    IN_PERSON = "IN_PERSON"
    FAMILY = "FAMILY"
    MATCHMAKER_PRESENT = "MATCHMAKER_PRESENT"


class FeedbackDecision(StrEnum):
    CONTINUE = "CONTINUE"
    STOP = "STOP"
    ANOTHER_MEETING = "ANOTHER_MEETING"


class SuccessFeeStatus(StrEnum):
    NONE = "NONE"
    PENDING = "PENDING"
    PAID = "PAID"
    WAIVED = "WAIVED"
