"""initial frozen schema

Revision ID: a66577795a04
Revises: 
Create Date: 2026-09-07 17:58:09.377972
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'a66577795a04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('governorate', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'MATCHMAKER', 'MALE_USER', name='role', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'BLOCKED', name='userstatus', native_enum=False), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_key', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('structured_state', sa.JSON(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_session_key'), 'conversations', ['session_key'], unique=True)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('male_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('characteristics', sa.JSON(), nullable=False),
    sa.Column('preferred_contact', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_male_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_male_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_male_profiles_user_id'))
    )
    op.create_table('matchmakers',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus', native_enum=False), nullable=False),
    sa.Column('governorates', sa.JSON(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_matchmakers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matchmakers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_matchmakers_user_id'))
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('reporter_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_table('female_leads',
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('governorate', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('preferred_time', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ASSIGNED', 'CONTACTED', 'PROFILE_CREATED', 'CLOSED', name='femaleleadstatus', native_enum=False), nullable=False),
    sa.Column('assigned_matchmaker_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_matchmaker_id'], ['matchmakers.id'], name=op.f('fk_female_leads_assigned_matchmaker_id_matchmakers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_female_leads'))
    )
    op.create_index(op.f('ix_female_leads_phone'), 'female_leads', ['phone'], unique=False)
    op.create_table('female_profiles',
    sa.Column('public_code', sa.String(length=30), nullable=False),
    sa.Column('matchmaker_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('exact_address', sa.Text(), nullable=True),
    sa.Column('private_notes', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('governorate', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=150), nullable=True),
    sa.Column('education_field', sa.String(length=150), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('children', sa.Boolean(), nullable=True),
    sa.Column('hijab_status', sa.String(length=50), nullable=True),
    sa.Column('religious_preference', sa.String(length=100), nullable=True),
    sa.Column('personality_traits', sa.JSON(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('public_summary', sa.Text(), nullable=True),
    sa.Column('desired_male', sa.JSON(), nullable=False),
    sa.Column('contact_preference', sa.Enum('GUARDIAN_FIRST', 'FAMILIES', 'MATCHMAKER', 'VIRTUAL_WITH_GUARDIAN', 'OTHER', name='contactpreference', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'HIDDEN', 'MATCHED', 'ARCHIVED', name='femaleprofilestatus', native_enum=False), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matchmaker_id'], ['matchmakers.id'], name=op.f('fk_female_profiles_matchmaker_id_matchmakers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_female_profiles'))
    )
    op.create_index(op.f('ix_female_profiles_governorate'), 'female_profiles', ['governorate'], unique=False)
    op.create_index(op.f('ix_female_profiles_matchmaker_id'), 'female_profiles', ['matchmaker_id'], unique=False)
    op.create_index(op.f('ix_female_profiles_public_code'), 'female_profiles', ['public_code'], unique=True)
    op.create_table('male_requests',
    sa.Column('request_code', sa.String(length=30), nullable=False),
    sa.Column('male_user_id', sa.String(length=36), nullable=False),
    sa.Column('male_characteristics', sa.JSON(), nullable=False),
    sa.Column('desired_female_characteristics', sa.JSON(), nullable=False),
    sa.Column('assigned_matchmaker_id', sa.String(length=36), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus', native_enum=False), nullable=False),
    sa.Column('workflow_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_matchmaker_id'], ['matchmakers.id'], name=op.f('fk_male_requests_assigned_matchmaker_id_matchmakers')),
    sa.ForeignKeyConstraint(['male_user_id'], ['users.id'], name=op.f('fk_male_requests_male_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_male_requests'))
    )
    op.create_index(op.f('ix_male_requests_is_active'), 'male_requests', ['is_active'], unique=False)
    op.create_index(op.f('ix_male_requests_male_user_id'), 'male_requests', ['male_user_id'], unique=False)
    op.create_index(op.f('ix_male_requests_request_code'), 'male_requests', ['request_code'], unique=True)
    op.create_index('uq_male_requests_one_active', 'male_requests', ['male_user_id'], unique=True, postgresql_where=sa.text('is_active = true'), sqlite_where=sa.text('is_active = 1'))
    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('match_candidates',
    sa.Column('male_request_id', sa.String(length=36), nullable=False),
    sa.Column('female_profile_id', sa.String(length=36), nullable=False),
    sa.Column('matchmaker_id', sa.String(length=36), nullable=True),
    sa.Column('male_to_female_score', sa.Float(), nullable=False),
    sa.Column('female_to_male_score', sa.Float(), nullable=False),
    sa.Column('mutual_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['female_profile_id'], ['female_profiles.id'], name=op.f('fk_match_candidates_female_profile_id_female_profiles')),
    sa.ForeignKeyConstraint(['male_request_id'], ['male_requests.id'], name=op.f('fk_match_candidates_male_request_id_male_requests')),
    sa.ForeignKeyConstraint(['matchmaker_id'], ['matchmakers.id'], name=op.f('fk_match_candidates_matchmaker_id_matchmakers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_candidates')),
    sa.UniqueConstraint('male_request_id', 'female_profile_id', name='uq_candidate_pair')
    )
    op.create_index(op.f('ix_match_candidates_female_profile_id'), 'match_candidates', ['female_profile_id'], unique=False)
    op.create_index(op.f('ix_match_candidates_male_request_id'), 'match_candidates', ['male_request_id'], unique=False)
    op.create_table('match_cases',
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('male_request_id', sa.String(length=36), nullable=False),
    sa.Column('female_profile_id', sa.String(length=36), nullable=False),
    sa.Column('matchmaker_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('CANDIDATE_SELECTED', 'MALE_VERIFICATION', 'PAYMENT_PENDING', 'READY_TO_CONTACT_FEMALE', 'WAITING_FEMALE', 'FEMALE_ACCEPTED', 'WAITING_MALE', 'MUTUAL_ACCEPTANCE', 'MEETING_SCHEDULED', 'MEETING_COMPLETED', 'FOLLOW_UP', 'SERIOUS_CONTACT', 'ENGAGED', 'MARRIED', 'REJECTED', 'CLOSED', name='matchcasestatus', native_enum=False), nullable=False),
    sa.Column('female_decision', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'NEED_MORE_INFO', name='decision', native_enum=False), nullable=False),
    sa.Column('male_decision', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'NEED_MORE_INFO', name='decision', native_enum=False), nullable=False),
    sa.Column('engaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('married_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success_fee_status', sa.Enum('NONE', 'PENDING', 'PAID', 'WAIVED', name='successfeestatus', native_enum=False), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['match_candidates.id'], name=op.f('fk_match_cases_candidate_id_match_candidates')),
    sa.ForeignKeyConstraint(['female_profile_id'], ['female_profiles.id'], name=op.f('fk_match_cases_female_profile_id_female_profiles')),
    sa.ForeignKeyConstraint(['male_request_id'], ['male_requests.id'], name=op.f('fk_match_cases_male_request_id_male_requests')),
    sa.ForeignKeyConstraint(['matchmaker_id'], ['matchmakers.id'], name=op.f('fk_match_cases_matchmaker_id_matchmakers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_cases')),
    sa.UniqueConstraint('candidate_id', name=op.f('uq_match_cases_candidate_id'))
    )
    op.create_index(op.f('ix_match_cases_male_request_id'), 'match_cases', ['male_request_id'], unique=False)
    op.create_table('match_case_history',
    sa.Column('match_case_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_match_case_history_actor_id_users')),
    sa.ForeignKeyConstraint(['match_case_id'], ['match_cases.id'], name=op.f('fk_match_case_history_match_case_id_match_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_case_history'))
    )
    op.create_index(op.f('ix_match_case_history_match_case_id'), 'match_case_history', ['match_case_id'], unique=False)
    op.create_table('meetings',
    sa.Column('match_case_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_type', sa.Enum('VIRTUAL', 'IN_PERSON', 'FAMILY', 'MATCHMAKER_PRESENT', name='meetingtype', native_enum=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_or_link', sa.Text(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_case_id'], ['match_cases.id'], name=op.f('fk_meetings_match_case_id_match_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings'))
    )
    op.create_index(op.f('ix_meetings_match_case_id'), 'meetings', ['match_case_id'], unique=False)
    op.create_table('payments',
    sa.Column('male_request_id', sa.String(length=36), nullable=False),
    sa.Column('match_case_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'WAIVED', 'REFUNDED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['male_request_id'], ['male_requests.id'], name=op.f('fk_payments_male_request_id_male_requests')),
    sa.ForeignKeyConstraint(['match_case_id'], ['match_cases.id'], name=op.f('fk_payments_match_case_id_match_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('reference', name=op.f('uq_payments_reference'))
    )
    op.create_index(op.f('ix_payments_male_request_id'), 'payments', ['male_request_id'], unique=False)
    op.create_table('meeting_feedback',
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('party', sa.String(length=10), nullable=False),
    sa.Column('decision', sa.Enum('CONTINUE', 'STOP', 'ANOTHER_MEETING', name='feedbackdecision', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_feedback_meeting_id_meetings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_feedback')),
    sa.UniqueConstraint('meeting_id', 'party', name='uq_feedback_party')
    )
    op.create_index(op.f('ix_meeting_feedback_meeting_id'), 'meeting_feedback', ['meeting_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_feedback_meeting_id'), table_name='meeting_feedback')
    op.drop_table('meeting_feedback')
    op.drop_index(op.f('ix_payments_male_request_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_meetings_match_case_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_match_case_history_match_case_id'), table_name='match_case_history')
    op.drop_table('match_case_history')
    op.drop_index(op.f('ix_match_cases_male_request_id'), table_name='match_cases')
    op.drop_table('match_cases')
    op.drop_index(op.f('ix_match_candidates_male_request_id'), table_name='match_candidates')
    op.drop_index(op.f('ix_match_candidates_female_profile_id'), table_name='match_candidates')
    op.drop_table('match_candidates')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('uq_male_requests_one_active', table_name='male_requests', postgresql_where=sa.text('is_active = true'), sqlite_where=sa.text('is_active = 1'))
    op.drop_index(op.f('ix_male_requests_request_code'), table_name='male_requests')
    op.drop_index(op.f('ix_male_requests_male_user_id'), table_name='male_requests')
    op.drop_index(op.f('ix_male_requests_is_active'), table_name='male_requests')
    op.drop_table('male_requests')
    op.drop_index(op.f('ix_female_profiles_public_code'), table_name='female_profiles')
    op.drop_index(op.f('ix_female_profiles_matchmaker_id'), table_name='female_profiles')
    op.drop_index(op.f('ix_female_profiles_governorate'), table_name='female_profiles')
    op.drop_table('female_profiles')
    op.drop_index(op.f('ix_female_leads_phone'), table_name='female_leads')
    op.drop_table('female_leads')
    op.drop_table('reports')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('matchmakers')
    op.drop_table('male_profiles')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_key'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
